Refactor dependency calculations
kovetskiy/manul pull request #31
Opened 2017-02-15 13:53 UTC by johansglock

- Now honors recursive flag (fixes kovetskiy/manul#30)
- Option to include testing dependencies (fixes kovetskiy/manul#15)
- Don't include recursive deps if they are already vendored (fixes kovetskiy/manul#3
- Don't vendor unused packages (fixes kovetskiy/manul#30)
- Do a got get at the beginning as a usability feature (fixes kovetskiy/manul#26)
- Should also fix kovetskiy/manulo#27, though unconfirmed

2017-02-15 13:55 UTC, johansglock commented
FYI, the tests fail in travis, I ran them manually locally, all output is what it's expected to be, though the test script itself fails.

2017-02-16 09:37 UTC, kovetskiy requested changes

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +				return imports, nil
why error is not returns here?

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +	cwd, _ := os.Getwd()
please do not ignore errors, better to return error than ignore it and produce abnormal output

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +		fmt.Fprintf(os.Stderr, "%s\n", out)
do not print on such nested function level, return error and print it where function has called

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +		return data, err
json.Unmarshal returns abmigious error when can't unmarshal json payload, so, please, add value from `out` variable to error message, like as following:
```
return data, fmt.Errof("can't unmarshal go list JSON output: %s\n%q", err, out)
```

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +	m := make(map[string]bool)
please do not use one-symbol variables, it is more clear when name of variable describes what the purpose (or meaning) of variable. 
u -> result
m -> hash or table

2017-02-16 09:37 UTC, kovetskiy commented on main.go
> +    -t --testing    Include testing dependencies.
may be here we should write something like `Include dependencies from tests?` What you think about it?

2017-02-16 09:37 UTC, kovetskiy commented on submodule.go
> +	cwd, _ := os.Getwd()
do not ignore error here.

Actually, it is 3th call of os.Getwd() may be create global variable `workdir` and initialize it in `init()` function?

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +			return imports, nil
why error is ignored?

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +				return imports, nil
and please wrap error with some useful message like (`error listing import: %s`, importName)

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +
please remove extra new line after last return statement

2017-02-16 09:37 UTC, kovetskiy commented on imports.go
> +type listOutput struct {
move this declaration to begin of the file, it is more obvious to find declaration of such structures when they are defined in the beginning of file

2017-02-16 09:39 UTC, kovetskiy commented
Hello. Thank you for the pull-request. I'm glad to see contributions like this.

Can you please add some testcases (for example for #30)?

2017-02-16 09:56 UTC, johansglock commented
Oh, the error handling was probably a last minute copy-paste mistake :) I will get around to fixing all of the requested changed later.

Regarding the tests; I would love to, if I could get the testing setup to run to begin with. Travis is failing as well. Any insights on these?

2017-02-16 10:03 UTC, kovetskiy commented
@johansglock I've fixed running tests in travis, now everything works as expected: https://travis-ci.org/kovetskiy/manul/builds/202185390

2017-02-16 10:56 UTC, kovetskiy commented on imports.go
> +		fmt.Fprintf(os.Stderr, "%s", err)
here should also return error on top level and print it in place where function parseImports has called

2017-02-16 10:57 UTC, johansglock commented on imports.go
> +		fmt.Fprintf(os.Stderr, "%s", err)
I think I'll just omit the print, there is not really a distinction between warnings and errors, so let's just omit the warning?

What do you think?

Still processing the rest btw.

2017-02-16 11:02 UTC, kovetskiy commented on imports.go
> +		fmt.Fprintf(os.Stderr, "%s", err)
Hmm, okay, keep it as is. anyway, you should replace calling from `Printf(stderr, "%s", err)` to `Println(err)` or add `\n` after `%s` for adding new line after error message.

2017-02-16 11:03 UTC, johansglock commented on imports.go
> +		fmt.Fprintf(os.Stderr, "%s", err)
Error is a propagation from the go commandline utility which already includes a newline.

2017-02-16 11:05 UTC, johansglock commented on imports.go
> +		fmt.Fprintf(os.Stderr, "%s", err)
Though I included it before; I'll add it again, it's nice to have the extra newline between the error and regular output

2017-02-16 11:09 UTC, kovetskiy commented on main.go
> +		panic(fmt.Errorf("couldn't get current working directory: %s", err))
I guess there is no need in panic's stack trace, just print error to os.Stderr.

2017-02-16 11:10 UTC, johansglock commented on main.go
> +		panic(fmt.Errorf("couldn't get current working directory: %s", err))
and os.Exit? this error is sort of crucial

2017-02-16 11:11 UTC, kovetskiy commented on main.go
> +		panic(fmt.Errorf("couldn't get current working directory: %s", err))
yes

2017-02-16 11:15 UTC, kovetskiy commented on imports.go
> +				return imports, fmt.Errorf("failed to list dependencies for testing package %s: %s", testImport, err)
please format line with max width as 80 symbols like as in existing code

2017-02-16 11:16 UTC, kovetskiy commented on imports.go
> +		return fmt.Errorf("couldn't 'go get' dependencies:\n%s", out)
on 143 line you use `can't` may be here replace `could` to `can`?

2017-02-16 11:18 UTC, kovetskiy commented on imports.go
> +	s := bufio.NewScanner(r)
wow, reader and scanner, may be just use strings.Split(strings.TrimSpaces(out), "\n")?

2017-02-16 11:32 UTC, johansglock commented
@robbertkl can you come up with some nice tests?

2017-02-16 11:44 UTC, robbertkl commented
@johansglock Who are you? Do I know you?

Not sure why I'm mentioned in this PR....

2017-02-24 04:54 UTC, kovetskiy commented
@johansglock I can add tests if you haven't a time to do it, can I merge it now?

2017-02-24 06:55 UTC, johansglock commented
This is safe to be merged yeah; haven't had time for the tests. So if you would be willing to do that, that would be great yeah!

2017-02-24 08:19 UTC, kovetskiy approved these changes

2017-02-24 08:19 UTC, merged

2017-02-24 08:21 UTC, kovetskiy commented
Merged, thanks for the contribution!